# Generated by Django 5.0 on 2023-12-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order_from_sun", models.IntegerField()),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                ("radius", models.IntegerField()),
            ],
        ),
    ]
