# Generated by Django 5.0 on 2023-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solar_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planet",
            name="image_url",
        ),
        migrations.AddField(
            model_name="planet",
            name="image",
            field=models.ImageField(default="images/Sun.png", upload_to="images/"),
        ),
    ]
